bug:
  - '(?i)(bug|error|exception|traceback|crash|not working|broken|failing|AttributeError|ValueError|TypeError|KeyError|ImportError|does not work|stopped working)'

enhancement:
  - '(?i)(feature|enhancement|feature request|add support|support for|request|wish|suggestion|could you|can you add)'

question:
  - '(?i)(question|how to|how do|what is|help|explain|why|where|where can|confused|understand)'

documentation:
  - '(?i)(docs|documentation|readme|example|wiki|manual|how to configure|guide)'

configuration:
  - '(?i)(config|setup|install|yaml|options|settings|configure|option|parameter)'

performance:
  - '(?i)(slow|performance|memory|cpu|hang|freeze|timeout|lagging|delayed)'

"home assistant":
  - '(?i)(home assistant|hass|HA \d+\.\d+|homeassistant|core \d+\.\d+)'

dependencies:
  - '(?i)(dependency|requirement|package|pip|version incompatible|requires|needs version)'
